### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by IsraAtGamings** [PrimusLV/Prison#1]
How to make it show on chat?
It say your group not in prison rank
How to add prison rank?

**Comment by PrimusLV** [comment]
Make sure you have any of rank that has been listed in config.yml

**Comment by IsraAtGamings** [comment]
@PrimusLV thanks it work and how to make a vip rankup rank ex {prefix} ][VIP just prefix change 
Soory bad english

**Comment by PrimusLV** [comment]
This plugin doesn't support that kind of functionality, you have to use other plugin for that. I guess you want same thing as ConflictPE has, right?

**Comment by IsraAtGamings** [comment]
Yea

**Comment by IsraAtGamings** [comment]
Add sign rankup :3

**Comment by PrimusLV** [comment]
Sign support will be added this friday but for now you can use TapToDo to do that.

**Comment by IsraAtGamings** [comment]
Ok :)

**Comment by PrimusLV** [comment]
https://github.com/PrimusLV/Prison/blob/master/src/prison/signs/Sign.php

**Comment by IsraAtGamings** [comment]
Guards and event for what thats?

**Comment by PrimusLV** [comment]
You will be able to capture events like RankUpEvent on your own plugin extending Prison functionality :)

**Comment by IsraAtGamings** [comment]
Hmm can i ask about economypshop ihave ask with onebone but he dont answerme maybe you know.
How to make first line sign line pshop it showing player name like XFury Server AvengeTech prison?
